config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :evenements

  resources :articles

  resources :rubriques

  devise_for :users, :controllers => { :sessions => "sessions" }

  root to: "home#index"
  get '/la-ville' => 'home#la_ville'
  get '/le-grand-magal' => 'home#le_grand_magal'
  get '/le-fondateur' => 'home#le_fondateur'
  get '/les-khalifs' => 'home#les_khalifs'

  get 'le_fondateur/index'

end

app/models/rubrique.rb
class Rubrique < ActiveRecord::Base
  extend FriendlyId
  friendly_id :titre, use:  [:slugged, :finders]

  has_many :articles
end

app/controllers/rubriques_controller.rb
class RubriquesController < ApplicationController
  before_action :set_rubrique, only: [:show, :edit, :update, :destroy]

  # GET /rubriques
  # GET /rubriques.json
  def index
    @rubriques = Rubrique.all
  end

  # GET /rubriques/1
  # GET /rubriques/1.json
  def show
  end

  # GET /rubriques/new
  def new
    @rubrique = Rubrique.new
  end

  # GET /rubriques/1/edit
  def edit
  end

  # POST /rubriques
  # POST /rubriques.json
  def create
    @rubrique = Rubrique.new(rubrique_params)

    respond_to do |format|
      if @rubrique.save
        format.html { redirect_to @rubrique, notice: 'Rubrique was successfully created.' }
        format.json { render :show, status: :created, location: @rubrique }
      else
        format.html { render :new }
        format.json { render json: @rubrique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubriques/1
  # PATCH/PUT /rubriques/1.json
  def update
    respond_to do |format|
      if @rubrique.update(rubrique_params)
        format.html { redirect_to @rubrique, notice: 'Rubrique was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubrique }
      else
        format.html { render :edit }
        format.json { render json: @rubrique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubriques/1
  # DELETE /rubriques/1.json
  def destroy
    @rubrique.destroy
    respond_to do |format|
      format.html { redirect_to rubriques_url, notice: 'Rubrique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubrique
      @rubrique = Rubrique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubrique_params
      params.require(:rubrique).permit(:titre, :descriptif, :status)
    end
end

app/views/rubriques/_form.html.erb
<%= form_for(rubrique) do |f| %>
  <% if rubrique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rubrique.errors.count, "error") %> prohibited this rubrique from being saved:</h2>

      <ul>
      <% rubrique.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :descriptif %><br>
    <%= f.text_field :descriptif %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubriques/edit.html.erb
<h1>Editing Rubrique</h1>

<%= render 'form' %>

<%= link_to 'Show', @rubrique %> |
<%= link_to 'Back', rubriques_path %>

app/views/rubriques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rubriques</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Descriptif</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rubriques.each do |rubrique| %>
      <tr>
        <td><%= rubrique.titre %></td>
        <td><%= rubrique.descriptif %></td>
        <td><%= rubrique.status %></td>
        <td><%= link_to 'Show', rubrique %></td>
        <td><%= link_to 'Edit', edit_rubrique_path(rubrique) %></td>
        <td><%= link_to 'Destroy', rubrique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rubrique', new_rubrique_path %>

app/views/rubriques/new.html.erb
<h1>New Rubrique</h1>

<%= render 'form', :rubrique => @rubrique %>

<%= link_to 'Back', rubriques_path %>

app/views/rubriques/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <p><h2>Article de la rubrique <%= @rubrique.titre.humanize %></h2></p>
  <div class="container">

    <% @rubrique.articles.each do |article| %>
        <div class="col-sm-6 col-md-4 col-xs-12">
          <div class="bs-component">
            <div>
              <% if article.image_a_la_une_file_name %>
                <%= image_tag(article.image_a_la_une(:medium), class:'thumb img-responsive', ) %>
              <% else %>
                  <img src="http://placehold.it/300x150" alt="">
              <% end %>
              </div>
            <h3><%= article.titre %></h3>
            <p><%= link_to 'Show more', article %></p>
            <p><%= article.created_at %></p>
          </div>
          <% if current_user %>
              <%= link_to 'Edit', edit_article_path(article) %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>

    <% end %>
  </div>

</div>