config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :evenements

  resources :articles

  resources :rubriques

  devise_for :users, :controllers => { :sessions => "sessions" }

  root to: "home#index"
  get '/la-ville' => 'home#la_ville'
  get '/le-grand-magal' => 'home#le_grand_magal'
  get '/le-fondateur' => 'home#le_fondateur'
  get '/les-khalifs' => 'home#les_khalifs'

  get 'le_fondateur/index'

end

app/models/evenement.rb
class Evenement < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :titre, :descriptif, :date, presence: true
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  before_action :set_evenement, only: [:show, :edit, :update, :destroy]

  # GET /evenements
  # GET /evenements.json
  def index
    @evenements = Evenement.all
  end

  # GET /evenements/1
  # GET /evenements/1.json
  def show
  end

  # GET /evenements/new
  def new
    @evenement = Evenement.new
  end

  # GET /evenements/1/edit
  def edit
  end

  # POST /evenements
  # POST /evenements.json
  def create
    @evenement = Evenement.new(evenement_params)

    respond_to do |format|
      if @evenement.save
        format.html { redirect_to @evenement, notice: 'Evenement was successfully created.' }
        format.json { render :show, status: :created, location: @evenement }
      else
        format.html { render :new }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evenements/1
  # PATCH/PUT /evenements/1.json
  def update
    respond_to do |format|
      if @evenement.update(evenement_params)
        format.html { redirect_to @evenement, notice: 'Evenement was successfully updated.' }
        format.json { render :show, status: :ok, location: @evenement }
      else
        format.html { render :edit }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evenements/1
  # DELETE /evenements/1.json
  def destroy
    @evenement.destroy
    respond_to do |format|
      format.html { redirect_to evenements_url, notice: 'Evenement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evenement
      @evenement = Evenement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evenement_params
      params.require(:evenement).permit(:image, :date, :titre, :descriptif, :status, :lieu, :latitude, :longitude)
    end
end

app/views/evenements/_form.html.erb
<%= simple_form_for(@evenement) do |f| %>
  <% if @evenement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evenement.errors.count, "error") %> prohibited this evenement from being saved:</h2>

      <ul>
      <% @evenement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
        <%= f.input :image, as: :file %>
    </div>
  <div class="field">
    <%= f.input :titre %>
  </div>
    <div class="field">
      <%= f.input :date %>
    </div>
  <div class="field">
    <%= cktext_area :evenement, :descriptif, :cols => 40, :ckeditor => {:uiColor => '#55C3A0', :toolbar => 'full'} %>
  </div>
  <div class="field">
    <%= f.input :status %>
  </div>
  <div class="field">
    <%= f.input :lieu %>
  </div>
  <div class="field">
    <%= f.input :latitude %>
  </div>
  <div class="field">
    <%= f.input :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evenements/edit.html.erb
<h1>Editing Evenement</h1>

<%= render 'form' %>

<%= link_to 'Show', @evenement %> |
<%= link_to 'Back', evenements_path %>

app/views/evenements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evenements</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Descriptif</th>
      <th>Status</th>
      <th>Lieu</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evenements.each do |evenement| %>
      <tr>
        <td><%= evenement.titre %></td>
        <td><%= evenement.descriptif %></td>
        <td><%= evenement.status %></td>
        <td><%= evenement.lieu %></td>
        <td><%= evenement.latitude %></td>
        <td><%= evenement.longitude %></td>
        <td><%= link_to 'Show', evenement %></td>
        <td><%= link_to 'Edit', edit_evenement_path(evenement) %></td>
        <td><%= link_to 'Destroy', evenement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evenement', new_evenement_path %>

app/views/evenements/new.html.erb
<div class="container">
<h1>New Evenement</h1>

<%= render 'form' %>

<%= link_to 'Back', evenements_path %>
</div>

app/views/evenements/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Titre:</strong>
      <%= @evenement.titre %>
    </p>

    <p>
      <strong>Descriptif:</strong>
      <%= @evenement.descriptif %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @evenement.status %>
    </p>

    <p>
      <strong>Lieu:</strong>
      <%= @evenement.lieu %>
    </p>

    <p>
      <strong>Latitude:</strong>
      <%= @evenement.latitude %>
    </p>

    <p>
      <strong>Longitude:</strong>
      <%= @evenement.longitude %>
    </p>

    <%= link_to 'Edit', edit_evenement_path(@evenement) %> |
    <%= link_to 'Back', evenements_path %>
</div>